In [1]:
import pandas as pd
from sklearn.metrics import accuracy_score
from sklearn.model_selection import train_test_split
from sklearn.tree import DecisionTreeClassifier

In [10]:
data = pd.read_csv('daily_weather.csv')

In [12]:
data.head(30)

,number,air_pressure_9am,air_temp_9am,avg_wind_direction_9am,avg_wind_speed_9am,max_wind_direction_9am,max_wind_speed_9am,rain_accumulation_9am,rain_duration_9am,relative_humidity_9am,relative_humidity_3pm
0,0,918.060000,74.822000,271.100000,2.080354,295.400000,2.863283,0.00,0.0,42.420000,36.160000
1,1,917.347688,71.403843,101.935179,2.443009,140.471548,3.533324,0.00,0.0,24.328697,19.426597
2,2,923.040000,60.638000,51.000000,17.067852,63.700000,22.100967,0.00,20.0,8.900000,14.460000
3,3,920.502751,70.138895,198.832133,4.337363,211.203341,5.190045,0.00,0.0,12.189102,12.742547
4,4,921.160000,44.294000,277.800000,1.856660,136.500000,2.863283,8.90,14730.0,92.410000,76.740000
5,5,915.300000,78.404000,182.800000,9.932014,189.000000,10.983375,0.02,170.0,35.130000,33.930000
6,6,915.598868,70.043304,177.875407,3.745587,186.606696,4.589632,0.00,0.0,10.657422,21.385657
7,7,918.070000,51.710000,242.400000,2.527742,271.600000,3.646212,0.00,0.0,80.470000,74.920000
8,8,920.080000,80.582000,40.700000,4.518619,63.000000,5.883152,0.00,0.0,29.580000,24.030000
9,9,915.010000,47.498000,163.100000,4.943637,195.900000,6.576604,0.00,0.0,88.600000,68.050000
10,10,919.650000,77.036000,70.600000,3.825167,85.500000,4.764682,0.00,0.0,22.070000,32.130000
11,11,915.640000,45.716000,241.600000,5.860783,265.800000,8.030615,0.55,1770.0,90.560000,79.090000
12,12,917.390000,49.784000,204.100000,1.275056,211.800000,2.013246,0.00,0.0,73.150000,58.430000
13,13,920.820000,62.438000,213.600000,2.617220,165.700000,3.310671,0.00,0.0,43.640000,27.990000
14,14,911.000000,86.432000,202.900000,1.207948,162.900000,1.677705,0.00,0.0,15.190000,24.370000
15,15,922.383131,70.865263,36.174175,1.847278,58.428632,2.529142,0.00,0.0,12.110889,14.801706
16,16,917.890000,NaN,169.200000,2.192201,196.800000,2.930391,0.00,0.0,48.990000,51.190000
17,17,916.915255,77.018961,234.539345,2.274725,229.474199,2.906513,0.00,0.0,21.031462,20.755683
18,18,918.800000,67.082000,176.100000,4.876529,183.400000,5.569981,0.00,0.0,18.900000,45.870000
19,19,922.040000,68.576000,58.300000,9.551734,81.900000,12.571603,0.00,0.0,7.540000,7.740000
20,20,919.992262,62.964383,54.799094,12.680436,74.254223,15.452306,0.00,0.0,18.809518,14.649909
21,21,917.230000,67.676000,177.800000,2.460634,93.200000,3.288302,0.00,0.0,40.640000,41.340000
22,22,921.125626,68.818772,71.799092,2.576538,95.472334,3.487444,0.00,0.0,11.742201,17.281161
23,23,920.350000,47.570000,192.100000,6.263432,205.700000,7.605596,0.00,0.0,54.550000,66.000000
24,24,921.788229,71.659572,217.405520,1.946447,253.758003,2.719712,0.00,0.0,11.194250,16.331716
25,25,918.030000,50.666000,128.900000,2.527742,117.400000,4.004123,0.00,0.0,76.880000,47.030000
26,26,914.490000,49.892000,163.000000,4.854160,189.600000,6.733189,0.00,0.0,92.100000,90.990000
27,27,914.900000,78.620000,203.300000,1.811921,240.000000,2.751436,0.00,220.0,47.890000,43.900000
28,28,915.840000,40.118000,171.900000,10.535987,188.000000,12.929513,0.00,0.0,86.430000,84.390000
29,29,916.310000,45.428000,183.100000,8.343786,194.600000,10.088599,0.00,0.0,86.150000,90.580000

In [13]:
data.size

12045

In [14]:
data.shape[0]

1095

In [15]:
data.shape

(1095, 11)

In [16]:
data[data.isnull().any(axis=1)]

,number,air_pressure_9am,air_temp_9am,avg_wind_direction_9am,avg_wind_speed_9am,max_wind_direction_9am,max_wind_speed_9am,rain_accumulation_9am,rain_duration_9am,relative_humidity_9am,relative_humidity_3pm
16,16,917.890000,NaN,169.200000,2.192201,196.800000,2.930391,0.000,0.000000,48.990000,51.190000
111,111,915.290000,58.820000,182.600000,15.613841,189.000000,NaN,0.000,0.000000,21.500000,29.690000
177,177,915.900000,NaN,183.300000,4.719943,189.900000,5.346287,0.000,0.000000,29.260000,46.500000
262,262,923.596607,58.380598,47.737753,10.636273,67.145843,13.671423,0.000,NaN,17.990876,16.461685
277,277,920.480000,62.600000,194.400000,2.751436,NaN,3.869906,0.000,0.000000,52.580000,54.030000
334,334,916.230000,75.740000,149.100000,2.751436,187.500000,4.183078,NaN,1480.000000,31.880000,32.900000
358,358,917.440000,58.514000,55.100000,10.021491,NaN,12.705819,0.000,0.000000,13.880000,25.930000
361,361,920.444946,65.801845,49.823346,21.520177,61.886944,25.549112,NaN,40.364018,12.278715,7.618649
381,381,918.480000,66.542000,90.900000,3.467257,89.400000,4.406772,NaN,0.000000,20.640000,14.350000
409,409,NaN,67.853833,65.880616,4.328594,78.570923,5.216734,0.000,0.000000,18.487385,20.356594
517,517,920.570000,53.600000,100.100000,4.697574,NaN,6.285801,4.712,14842.000000,79.880000,84.530000
519,519,916.250000,55.670000,176.400000,6.666081,188.200000,NaN,0.000,0.000000,72.550000,74.390000
546,546,NaN,42.746000,251.100000,12.929513,274.400000,17.604718,14.627,7825.000000,87.870000,70.770000
620,620,921.200000,56.786000,192.300000,9.551734,201.400000,11.005745,NaN,0.000000,59.790000,77.750000
625,625,912.400000,50.774000,171.600000,NaN,181.400000,4.831790,0.000,0.000000,86.840000,64.740000
656,656,920.830000,66.344000,NaN,15.457255,189.400000,16.486248,0.000,0.000000,23.770000,51.630000
670,670,910.920000,48.362000,156.500000,NaN,177.500000,16.128337,4.970,10560.000000,80.560000,88.220000
672,672,922.448945,72.863773,NaN,3.682370,214.196160,4.849450,0.000,0.000000,16.753670,17.804720
705,705,911.900000,59.072000,199.800000,1.275056,239.500000,1.834291,NaN,0.000000,77.630000,59.130000
731,731,922.970166,51.391847,33.810942,NaN,59.290089,11.111555,0.000,4.735034,34.807753,18.418179
737,737,917.895130,76.804690,104.771020,1.632705,97.178763,NaN,0.000,0.000000,13.771311,16.792455
788,788,917.923442,73.249717,42.101739,4.132698,64.284969,5.345258,0.000,NaN,6.939692,18.793825
840,840,918.043767,NaN,181.774042,0.964376,185.618601,1.570007,0.000,0.000000,11.911222,18.154358
848,848,915.250000,37.562000,246.500000,11.587349,258.700000,NaN,3.171,2891.000000,91.000000,90.780000
861,861,919.065408,NaN,172.303728,2.639600,193.058141,3.326949,0.000,0.000000,12.497839,13.438518
869,869,NaN,45.104000,259.000000,3.265932,275.000000,4.026492,0.000,80.000000,85.270000,90.260000
998,998,914.140000,71.240000,NaN,1.722444,232.900000,2.326418,0.000,0.000000,24.200000,41.380000
1031,1031,922.669195,NaN,47.946284,7.969686,65.770066,10.262337,0.000,0.000000,18.920805,19.641841
1035,1035,919.670000,77.576000,171.800000,6.554234,191.000000,8.164831,0.000,NaN,56.860000,50.650000
1063,1063,917.300185,65.790001,NaN,1.879553,222.498226,2.692862,0.000,0.000000,14.972668,20.966267
1066,1066,919.564869,73.726732,68.704694,3.551777,102.571616,4.861315,NaN,0.000000,11.657314,17.331823

In [17]:
data.shape[0]

1095

In [18]:
del data['number']

In [19]:
data.shape

(1095, 10)

In [20]:
data = data.dropna()

In [21]:
data.shape

(1064, 10)

In [22]:
clean_data = data.copy()

In [24]:
clean_data['humidity_label'] = (clean_data['relative_humidity_3pm'] > 24.99) * 1

In [25]:
y = clean_data['humidity_label'].copy()

In [34]:
y.shape

(1064,)

In [29]:
features = ['air_pressure_9am','air_temp_9am','avg_wind_direction_9am','avg_wind_speed_9am','max_wind_direction_9am','max_wind_speed_9am','rain_accumulation_9am','rain_duration_9am', 'relative_humidity_9am']

In [30]:
x = clean_data[features].copy()

In [35]:
x.shape

(1064, 9)

In [39]:
x_train, x_test, y_train, y_test = train_test_split(x, y, test_size = 0.33, random_state = 324)

In [40]:
x_train.shape

(712, 9)

In [41]:
x_test.shape

(352, 9)

In [42]:
y_train.shape

(712,)

In [43]:
y_test.shape

(352,)

In [45]:
type(x_train), type(x_test), type(y_train), type(y_test)

(pandas.core.frame.DataFrame,
 pandas.core.frame.DataFrame,
 pandas.core.series.Series,
 pandas.core.series.Series)

In [46]:
classifier = DecisionTreeClassifier(max_leaf_nodes = 10, random_state = 0)
classifier.fit(x_train, y_train)

DecisionTreeClassifier(class_weight=None, criterion='gini', max_depth=None,
            max_features=None, max_leaf_nodes=10,
            min_impurity_decrease=0.0, min_impurity_split=None,
            min_samples_leaf=1, min_samples_split=2,
            min_weight_fraction_leaf=0.0, presort=False, random_state=0,
            splitter='best')

In [47]:
type(classifier)

sklearn.tree.tree.DecisionTreeClassifier

In [49]:
y_predictions = classifier.predict(x_test)

In [53]:
type(y_predictions)

numpy.ndarray

In [54]:
accuracy_score(y_true = y_test, y_pred = predictions)

0.9005681818181818